### ISSUE TITLE
Module not found error: 'edgegrid'

### ISSUE THREAD

**Issue by ynohat** [akamai/cli-edgeworkers#55]
```
❯ nvm version
v14.15.1

❯ akamai install edgeworkers
Attempting to fetch command from https://github.com/akamai/cli-edgeworkers.git... ... [OK]
Installing... ... [OK]

Installed Commands:

  auth (alias: auth/auth)
    Interface for Akamai Edgegrid Authentication
  config
    Manage configuration
  dns (alias: dns/dns)
    Manage DNS zones with Edge DNS
  edgekv (aliases: ekv, edgekv, edgeworkers/edgekv)
    Manage Akamai EdgeKV database.
  edgeworkers (aliases: ew, edgeworkers, edgeworkers/edgeworkers)
    Manage Akamai EdgeWorkers code bundles.
(...)

❯ akamai edgeworkers
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'edgegrid'
Require stack:
- /Users/ahogg/.akamai-cli/src/cli-edgeworkers/bin/src/utils/env-utils.js
- /Users/ahogg/.akamai-cli/src/cli-edgeworkers/bin/src/edgeworkers/ew-cli-main.js
- /Users/ahogg/.akamai-cli/src/cli-edgeworkers/akamai-edgeworkers
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/ahogg/.akamai-cli/src/cli-edgeworkers/bin/src/utils/env-utils.js:23:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ahogg/.akamai-cli/src/cli-edgeworkers/bin/src/utils/env-utils.js',
    '/Users/ahogg/.akamai-cli/src/cli-edgeworkers/bin/src/edgeworkers/ew-cli-main.js',
    '/Users/ahogg/.akamai-cli/src/cli-edgeworkers/akamai-edgeworkers'
  ]
}

❯ cat cli-edgeworkers/cli.json 
{
  "requirements": {
    "node": "7.0.0"
  },
  "commands": [
    {
      "name": "edgeworkers",
      "version": "1.4.1",
      "aliases": ["ew", "edgeworkers"],
      "description": "Manage Akamai EdgeWorkers code bundles."
    },
    {
      "name": "edgekv",
      "version": "1.4.1",
      "aliases": ["ekv", "edgekv"],
      "description": "Manage Akamai EdgeKV database."
    }
  ]
}
```

Among other things, this is breaking akamai docker builds.

**Comment by bmatthew** [comment]
Thanks for noticing this, I hadn't realized the code would get pulled in without a new version release but there was also an oversight on upgrade of the 'edgegrid' package to 'akamai-edgegrid'.
